version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 114614701773.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - docker build -t my-pipeline .
      - ddocker tag my-pipeline:latest 114614701773.dkr.ecr.us-east-1.amazonaws.com/my-pipeline:latest

  post_build:
    commands:
      - docker push 114614701773.dkr.ecr.us-east-1.amazonaws.com/my-pipeline:latest

  
      - printf '[{"name":"my-pipeline","imageUri":"%s"}]' 1114614701773.dkr.ecr.us-east-1.amazonaws.com/my-pipeline > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    
