version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 114614701773.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - echo "===== INDEX.HTML CONTENT ====="
      - cat index.html
      - echo "============================="
      - docker build -t my-app-image:$CODEBUILD_BUILD_NUMBER .
      - docker tag my-app-image:$CODEBUILD_BUILD_NUMBER 114614701773.dkr.ecr.ap-south-1.amazonaws.com/my-app-image:$CODEBUILD_BUILD_NUMBER

  post_build:
    commands:
      - docker push 114614701773.dkr.ecr.ap-south-1.amazonaws.com/my-app-image:$CODEBUILD_BUILD_NUMBER
      - printf '[{"name":"my-pipeline","imageUri":"114614701773.dkr.ecr.ap-south-1.amazonaws.com/my-app-image:%s"}]' $CODEBUILD_BUILD_NUMBER > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
